[theme]
theme = "modern"

[icons]
icons = "material-nf"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:30,rot_interval:0.5) $prev $play $next |}"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 1
warning_mem = 70
critical_mem = 90

[[block]]
block = "battery"
format = " $icon  $percentage "
missing_format = ""

[[block]]
block = "custom"
command = "xkblayout-state print %s"
format = " $text"
interval = 1

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d.%m  %R') "
short = " $icon $timestamp.datetime(f:%R) "

